[package]
name = "test"
version = "0.1.0"
authors = ["Philip Van Raalte <phil.vanraalte@gmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "test"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
num_cpus = "1.4.0"